name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run health check
        run: python3 health_check.py

      - name: Deploy to production
        run: python3 deploy.py
